name: Build and Deploy Code

on: 
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3 
      - name: Install python version 3.9
        uses:  actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt 