name: Build and Deploy Code

on: 
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3 
      - name: say hi to das
        run: echo "hello das"